/**
 * Seed script for test data
 * Populates the database with mock user, emails, tasks, and meetings for testing
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding test data...');

  // Create test user
  const user = await prisma.user.upsert({
    where: { email: 'test@example.com' },
    update: {},
    create: {
      email: 'test@example.com',
      microsoftId: 'test-microsoft-id-12345',
      accessToken: 'mock-access-token',
      refreshToken: 'mock-refresh-token',
      tokenExpiry: new Date(Date.now() + 3600000), // 1 hour from now
    },
  });

  console.log('✓ Created test user:', user.email);

  // Create agent settings
  await prisma.agentSettings.upsert({
    where: { userId: user.id },
    update: {},
    create: {
      userId: user.id,
      enabled: true,
      autoProcessEmails: true,
      autoGenerateDrafts: false,
      autoExtractMeetings: true,
      requireApprovalForSend: true,
      checkIntervalMinutes: 15,
    },
  });

  console.log('✓ Created agent settings');

  // Create test emails
  const emails = [
    {
      outlookId: 'email-001',
      subject: 'Quarterly Business Review - Q1 2026',
      from: 'john.doe@contoso.com',
      body: 'Hi team, I wanted to schedule our Q1 business review meeting for next week. Please let me know your availability for Tuesday or Wednesday afternoon.',
      receivedAt: new Date('2026-01-15T10:00:00Z'),
      processed: false,
    },
    {
      outlookId: 'email-002',
      subject: 'Project Update: Website Redesign',
      from: 'sarah.smith@fabrikam.com',
      body: 'The website redesign project is progressing well. We have completed the wireframes and are moving into the design phase. Expected completion is end of February.',
      receivedAt: new Date('2026-01-16T14:30:00Z'),
      processed: false,
    },
    {
      outlookId: 'email-003',
      subject: 'Action Required: Approve Budget for Marketing Campaign',
      from: 'marketing@company.com',
      body: 'Please review and approve the attached budget for our Q2 marketing campaign. We need approval by end of this week to proceed with vendor contracts.',
      receivedAt: new Date('2026-01-17T09:15:00Z'),
      processed: false,
    },
    {
      outlookId: 'email-004',
      subject: 'Meeting Invitation: Product Strategy Discussion',
      from: 'mike.johnson@company.com',
      body: 'You are invited to join our product strategy discussion on January 25th at 2:00 PM. Location: Conference Room A. We will discuss roadmap priorities for H1 2026.',
      receivedAt: new Date('2026-01-18T11:00:00Z'),
      processed: false,
    },
    {
      outlookId: 'email-005',
      subject: 'Customer Feedback: Feature Request',
      from: 'feedback@customerportal.com',
      body: 'We have received feedback from several enterprise customers requesting bulk export functionality. This could be a valuable addition to our Q2 roadmap.',
      receivedAt: new Date('2026-01-19T15:45:00Z'),
      processed: false,
    },
  ];

  for (const emailData of emails) {
    await prisma.email.upsert({
      where: { outlookId: emailData.outlookId },
      update: {},
      create: {
        ...emailData,
        userId: user.id,
      },
    });
  }

  console.log(`✓ Created ${emails.length} test emails`);

  // Create test tasks
  const tasks = [
    {
      title: 'Review Q1 budget proposal',
      description: 'Review the budget proposal from marketing team',
      priority: 'high',
      status: 'todo',
      category: 'finance',
      dueDate: new Date('2026-01-22T17:00:00Z'),
    },
    {
      title: 'Prepare presentation for client meeting',
      description: 'Create slides for upcoming client presentation',
      priority: 'medium',
      status: 'in_progress',
      category: 'sales',
      dueDate: new Date('2026-01-25T12:00:00Z'),
    },
    {
      title: 'Code review for feature branch',
      description: 'Review pull request #234 for new authentication feature',
      priority: 'medium',
      status: 'todo',
      category: 'engineering',
    },
  ];

  for (const taskData of tasks) {
    await prisma.task.create({
      data: {
        ...taskData,
        userId: user.id,
      },
    });
  }

  console.log(`✓ Created ${tasks.length} test tasks`);

  // Create test meetings
  const meetings = [
    {
      title: 'Q1 Business Review',
      startTime: new Date('2026-01-28T14:00:00Z'),
      endTime: new Date('2026-01-28T15:30:00Z'),
      location: 'Conference Room B',
      attendees: 'john.doe@contoso.com, sarah.smith@fabrikam.com',
      description: 'Quarterly business review meeting to discuss Q1 results and Q2 planning',
      category: 'business',
    },
    {
      title: 'Product Strategy Discussion',
      startTime: new Date('2026-01-25T14:00:00Z'),
      endTime: new Date('2026-01-25T15:00:00Z'),
      location: 'Conference Room A',
      attendees: 'mike.johnson@company.com, team@company.com',
      description: 'Discussion of H1 2026 product roadmap priorities',
      agenda: '1. Review current roadmap\n2. Discuss customer feedback\n3. Prioritize features',
      category: 'product',
    },
  ];

  for (const meetingData of meetings) {
    await prisma.meeting.create({
      data: {
        ...meetingData,
        userId: user.id,
      },
    });
  }

  console.log(`✓ Created ${meetings.length} test meetings`);

  // Create test drafts
  const drafts = [
    {
      subject: 'Re: Quarterly Business Review - Q1 2026',
      body: 'Thank you for reaching out. I am available on Tuesday afternoon from 2-4 PM or Wednesday from 1-3 PM. Please let me know which time works best for the team.',
      toRecipients: 'john.doe@contoso.com',
      status: 'draft',
    },
  ];

  for (const draftData of drafts) {
    await prisma.draft.create({
      data: {
        ...draftData,
        userId: user.id,
      },
    });
  }

  console.log(`✓ Created ${drafts.length} test drafts`);

  // Create test extension opportunity
  const opportunity = await prisma.extensionOpportunity.create({
    data: {
      userId: user.id,
      companyName: 'Contoso Industries',
      industry: 'Manufacturing',
      companySize: '5000-10000',
      location: 'Seattle, WA',
      domainExpertise: 'Supply chain management and logistics optimization',
      hasData: true,
      hasTechCapability: true,
      microsoftRelationship: 'Enterprise customer - 3+ years',
      m365Usage: 'Teams, SharePoint, Power Platform',
      extensionIdea: 'Supply chain visibility Copilot extension with real-time tracking',
      targetMarket: 'Manufacturing and logistics companies',
      potentialValue: 'High - addresses major pain point',
      opportunityScore: 85,
      priority: 'high',
      stage: 'discovery',
      discoverySource: 'Customer meeting',
      discoveredDate: new Date('2026-01-10T00:00:00Z'),
      nextAction: 'Schedule technical deep-dive call',
      nextActionDate: new Date('2026-01-30T00:00:00Z'),
    },
  });

  console.log('✓ Created test extension opportunity');

  // Create extension contacts
  await prisma.extensionContact.create({
    data: {
      opportunityId: opportunity.id,
      name: 'Alice Thompson',
      title: 'VP of Operations',
      role: 'Decision Maker',
      linkedInUrl: 'https://linkedin.com/in/alice-thompson',
      email: 'alice.thompson@contoso.com',
      warmIntroPath: 'Via Sarah Smith',
      relationshipStrength: 'warm',
      mutualConnections: 5,
      outreachStatus: 'contacted',
      lastContactDate: new Date('2026-01-15T00:00:00Z'),
      lastContactType: 'email',
      linkedInActive: true,
    },
  });

  console.log('✓ Created extension contacts');

  console.log('\n✨ Test data seeding complete!');
  console.log('\nTest User Credentials:');
  console.log('  Email: test@example.com');
  console.log('  Microsoft ID: test-microsoft-id-12345');
}

main()
  .catch((e) => {
    console.error('Error seeding data:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
